# .github/workflows/dispatch-master.yml

name: Dispatch Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [ triggered-by-repo-a-update ]
jobs:
  build-master:
    uses: ./.github/workflows/build-reusable.yml
    with:
      branch: master
      ref: refs/heads/master
    secrets:
      REPO_B_DISPATCH_TOKEN: ${{ secrets.REPO_B_DISPATCH_TOKEN }}